### PR TITLE
Include wide-area lookups in cache dump

### PR DESCRIPTION
**Pull request by pemensik**
Include counts of dead entries in mdns resolution. Include lookups active and dead for wide-area. Attempt to debug easier PR#411 issue.

### CODE REVIEW

**Comment by pemensik** [comment]
This change should make easier to debug issue in PR #411. It logs also number of dead entries and wide-area lookups in progress or dead.

**Comment by pemensik** [comment]
This dump is created by ``sudo kill -SIGUSR1 $(pidof avahi-daemon)`` command.

**Comment by evverx** [comment]
I wonder if it should be closed? That issue was resolved so it's no longer necessary to dump that data.

I guess in general it would be nice to make avahi more introspectable but that interface should probably be separate from the cache.

**Comment by evverx** [comment]
Let's close this.

**Pull request closed without merging**
