### PR TITLE
Update Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by rffontenelle**

### CODE REVIEW

**Comment by rffontenelle** [comment]
Would it be possible to merge this PR from 5 months ago? It is merely a translation fix, nothing hard to review.

**Comment by rffontenelle** [comment]
Hi there. Can this tiny translation fix please be merged?

**Comment by rffontenelle** [comment]
Just an yearly reminder of this simple PR to be merged. Thanks

**Comment by pemensik** [comment]
Thank you for your patience, merging it.

**Pull request merged**
