### PR TITLE
Updated Hungarian translation

### PR DESCRIPTION
**Pull request by urbalazs**
Hi @lathiat 
Here is the updated Hungarian translation for Avahi.

### CODE REVIEW

**Comment by urbalazs** [comment]
Hi @lathiat 
Any reason why this PR is not merged yet?

**Comment by urbalazs** [comment]
Hi @lathiat 
Any reason why this PR is not merged yet?

**Comment by lathiat** [comment]
Thanks for your contribution, apologies for the delay in merging.  I merged an older request which mostly made the same changes, except for this.  Can you let me know if it makes sense to still Merge this part?
```
<<<<<<< hun
msgstr "_Mégse"
=======
msgstr "Mé_gse"
>>>>>>> master
```

**Comment by urbalazs** [comment]
Hi @lathiat 
Thank you for the merging. I changed the mnemonic key, because in case of some GUIs the letter g makes invisible the underline mark (because of its part under baseline).

**Comment by urbalazs** [comment]
The Hungarian translation is done by kelemeng.

**Pull request closed without merging**
